name: Continous Delivery

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set up testcontainers reuse
        run: |
          echo "testcontainers.reuse.enable=true" >> ~/.testcontainers.properties

      - name: Build, publish to GPR and tag
        run: |
          if [ "$GITHUB_REPOSITORY" == "gruelbox/transaction-outbox" ]; then
            revision="6.0.$GITHUB_RUN_NUMBER"
            echo "Building $revision at $GITHUB_SHA"
            mvn -Pconcise,delombok -B deploy -s $GITHUB_WORKSPACE/settings.xml -Drevision="$revision" -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            echo "Tagging $revision"
            git tag $revision
            git push origin $revision
          else
            mvn -Pconcise,delombok -B package -fae -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
