name: Version 2 snapshots

on:
  push:
    branches: [r2dbc4]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build, publish to GPR and tag
        run: |
          if [ "$GITHUB_REPOSITORY" == "gruelbox/transaction-outbox" ]; then
            revision="2.1.$GITHUB_RUN_NUMBER-SNAPSHOT"
            echo "Building $revision at $GITHUB_SHA"
            mvn -Pdelombok -B deploy -s $GITHUB_WORKSPACE/settings.xml -Drevision="$revision"
            echo "Tagging $revision"
            git tag $revision
            git push origin $revision
          else
            mvn -Pdelombok -B package
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
